module Pages.Confirm.View exposing (..)
import Html exposing (..)
import Html.Attributes exposing (..)
import Json.Encode exposing (string)
import Model

view : Model.Model -> Html msg
view appModel =
  div [ class "container col-md-4 order-md-2 mb-4" ]
    [ h4 [ class "d-flex justify-content-between align-items-center mb-3" ]
        [ span [ class "text-muted" ]
            [ text "Your Order has been placed!" ]
        ]
    , ul [ class "list-group mb-3" ]
        [ li [ class "list-group-item d-flex justify-content-between lh-condensed" ]
            [ div []
                [ h6 [ class "my-0" ]
                    [ text "Order Ref." ]
                , small [ class "text-muted" ]
                    [ text "Brief description" ]
                ]
            , span [ class "text-muted" ]
                [ text "12345" ]
            ]
        , li [ class "list-group-item d-flex justify-content-between lh-condensed" ]
            [ div []
                [ h6 [ class "my-0" ]
                    [ text "Cash" ]
                , small [ class "text-muted" ]
                    [ text "Brief description" ]
                ]
            , span [ class "text-muted" ]
                [ text ("$" ++ toString appModel.exchangePageModel.usdAmount) ]
            ]
        , li [ class "list-group-item d-flex justify-content-between lh-condensed" ]
            [ div []
                [ h6 [ class "my-0" ]
                    [ text "Sell Rate" ]
                , small [ class "text-muted" ]
                    [ text "Brief description" ]
                ]
            , span [ class "text-muted" ]
                [ text (toString appModel.exchangePageModel.exchangeRate) ]
            ]
        , li [ class "list-group-item d-flex justify-content-between bg-light" ]
            [ div [ class "text-success" ]
                [ h6 [ class "my-0" ]
                    [ text "You Pay" ]
                , small []
                    [ text "Brief description" ]
                ]
            , span [ class "text-success", property "innerHTML" (string( "&pound;" ++ toString appModel.exchangePageModel.gbpAmount) ) ]
                [  ]
            ]
        ]
    , Html.form [ class "card p-2" ]
        [ div [ class "input-group" ]
            [ a [ class "btn btn-lg btn-primary", href "#", attribute "role" "button" ]
                [ text "Book Another" ]
            ]
        ]
    ]
